version: '3'

services:
  traefik:
    hostname: traefik
    container_name: traefik
    image: traefik:latest
    restart: always
    domainname: abcdef.com
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/traefik.toml:/traefik.toml
      - ${PWD}/acme.json:/acme.json
      - ${PWD}/rules.toml:/etc/traefik/rules.toml
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:abcdef.com; PathPrefixStrip: /traefik"
      - "traefik.port=80"
      - "traefik.port=8080"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=abcdef.com"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
    networks:
      - traefik_proxy
networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
